---
title: "Problema 54"
output: html_document
date: "2024-02-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Problema.** The presence of colorectal cancer can be tested via a fecal occult blood count test. Sometimes the test can give a positive result when the cancer is absent and sometimes the test records a negative when in fact the cancer is present. In a population of 10,000 adults screened for colorectal cancer via a fecal blood test, the following counts were recorded.

|               |  Cancer Present              |       No Cancer    |
|:---------------:|:----------------:|:-----------:|
| Test positive | 20             | 294       |
| Test negative | 10             | 9676      |

Based on this information, find (to 3 decimal places) the **odds** that a person in the population has colorectal cancer given that their fecal occult blood test was positive.

**Solución.** Consideremos los siguientes eventos:

-   $T$: el test da positivo.

-   $C$: el paciente tiene cáncer.

El problema pide calcular $P(C\mid T)$. Tenemos que$$P(C\mid T)=\dfrac{P(C\cap T)}{P(T)}=\dfrac{\dfrac{20}{10000}}{\dfrac{314}{10000}}=\frac{20}{314}$$

Así, las probabilidades (*odds*) son la relación de que el cáncer sí este presente a que no:$$\dfrac{P(C\mid T)}{P(\overline C\mid T)}=\dfrac{\dfrac{20}{314}}{1-\dfrac{20}{314}}=\dfrac{20}{294}=\dfrac{10}{147}.$$
